//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SRHF.wrUSG {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsUSGSoap", Namespace="http://tempuri.org/")]
    public partial class wsUSG : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUSGByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUSGByEMROperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUSGByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUSGByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDailyNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMonthlyNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYearlyNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsUSG() {
            this.Url = global::SRHF.Properties.Settings.Default.SRHF_wrUSG_wsUSG;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUSGCompletedEventHandler GetUSGCompleted;
        
        /// <remarks/>
        public event GetUSGByIDCompletedEventHandler GetUSGByIDCompleted;
        
        /// <remarks/>
        public event GetUSGByEMRCompletedEventHandler GetUSGByEMRCompleted;
        
        /// <remarks/>
        public event GetUSGByDateCompletedEventHandler GetUSGByDateCompleted;
        
        /// <remarks/>
        public event GetUSGByDatesCompletedEventHandler GetUSGByDatesCompleted;
        
        /// <remarks/>
        public event AddUSGCompletedEventHandler AddUSGCompleted;
        
        /// <remarks/>
        public event UpdateUSGCompletedEventHandler UpdateUSGCompleted;
        
        /// <remarks/>
        public event DeleteUSGCompletedEventHandler DeleteUSGCompleted;
        
        /// <remarks/>
        public event GetDailyNoCompletedEventHandler GetDailyNoCompleted;
        
        /// <remarks/>
        public event GetMonthlyNoCompletedEventHandler GetMonthlyNoCompleted;
        
        /// <remarks/>
        public event GetYearlyNoCompletedEventHandler GetYearlyNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUSG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetUSG() {
            object[] results = this.Invoke("GetUSG", new object[0]);
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetUSGAsync() {
            this.GetUSGAsync(null);
        }
        
        /// <remarks/>
        public void GetUSGAsync(object userState) {
            if ((this.GetUSGOperationCompleted == null)) {
                this.GetUSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUSGOperationCompleted);
            }
            this.InvokeAsync("GetUSG", new object[0], this.GetUSGOperationCompleted, userState);
        }
        
        private void OnGetUSGOperationCompleted(object arg) {
            if ((this.GetUSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUSGCompleted(this, new GetUSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUSGByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public USG GetUSGByID(int ID) {
            object[] results = this.Invoke("GetUSGByID", new object[] {
                        ID});
            return ((USG)(results[0]));
        }
        
        /// <remarks/>
        public void GetUSGByIDAsync(int ID) {
            this.GetUSGByIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void GetUSGByIDAsync(int ID, object userState) {
            if ((this.GetUSGByIDOperationCompleted == null)) {
                this.GetUSGByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUSGByIDOperationCompleted);
            }
            this.InvokeAsync("GetUSGByID", new object[] {
                        ID}, this.GetUSGByIDOperationCompleted, userState);
        }
        
        private void OnGetUSGByIDOperationCompleted(object arg) {
            if ((this.GetUSGByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUSGByIDCompleted(this, new GetUSGByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUSGByEMR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetUSGByEMR(string EMRNo) {
            object[] results = this.Invoke("GetUSGByEMR", new object[] {
                        EMRNo});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetUSGByEMRAsync(string EMRNo) {
            this.GetUSGByEMRAsync(EMRNo, null);
        }
        
        /// <remarks/>
        public void GetUSGByEMRAsync(string EMRNo, object userState) {
            if ((this.GetUSGByEMROperationCompleted == null)) {
                this.GetUSGByEMROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUSGByEMROperationCompleted);
            }
            this.InvokeAsync("GetUSGByEMR", new object[] {
                        EMRNo}, this.GetUSGByEMROperationCompleted, userState);
        }
        
        private void OnGetUSGByEMROperationCompleted(object arg) {
            if ((this.GetUSGByEMRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUSGByEMRCompleted(this, new GetUSGByEMRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUSGByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetUSGByDate(System.DateTime dt) {
            object[] results = this.Invoke("GetUSGByDate", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetUSGByDateAsync(System.DateTime dt) {
            this.GetUSGByDateAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetUSGByDateAsync(System.DateTime dt, object userState) {
            if ((this.GetUSGByDateOperationCompleted == null)) {
                this.GetUSGByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUSGByDateOperationCompleted);
            }
            this.InvokeAsync("GetUSGByDate", new object[] {
                        dt}, this.GetUSGByDateOperationCompleted, userState);
        }
        
        private void OnGetUSGByDateOperationCompleted(object arg) {
            if ((this.GetUSGByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUSGByDateCompleted(this, new GetUSGByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUSGByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetUSGByDates(System.DateTime df, System.DateTime dt) {
            object[] results = this.Invoke("GetUSGByDates", new object[] {
                        df,
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetUSGByDatesAsync(System.DateTime df, System.DateTime dt) {
            this.GetUSGByDatesAsync(df, dt, null);
        }
        
        /// <remarks/>
        public void GetUSGByDatesAsync(System.DateTime df, System.DateTime dt, object userState) {
            if ((this.GetUSGByDatesOperationCompleted == null)) {
                this.GetUSGByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUSGByDatesOperationCompleted);
            }
            this.InvokeAsync("GetUSGByDates", new object[] {
                        df,
                        dt}, this.GetUSGByDatesOperationCompleted, userState);
        }
        
        private void OnGetUSGByDatesOperationCompleted(object arg) {
            if ((this.GetUSGByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUSGByDatesCompleted(this, new GetUSGByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddUSG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client AddUSG(USG usg) {
            object[] results = this.Invoke("AddUSG", new object[] {
                        usg});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void AddUSGAsync(USG usg) {
            this.AddUSGAsync(usg, null);
        }
        
        /// <remarks/>
        public void AddUSGAsync(USG usg, object userState) {
            if ((this.AddUSGOperationCompleted == null)) {
                this.AddUSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUSGOperationCompleted);
            }
            this.InvokeAsync("AddUSG", new object[] {
                        usg}, this.AddUSGOperationCompleted, userState);
        }
        
        private void OnAddUSGOperationCompleted(object arg) {
            if ((this.AddUSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUSGCompleted(this, new AddUSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUSG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateUSG(USG usg) {
            object[] results = this.Invoke("UpdateUSG", new object[] {
                        usg});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUSGAsync(USG usg) {
            this.UpdateUSGAsync(usg, null);
        }
        
        /// <remarks/>
        public void UpdateUSGAsync(USG usg, object userState) {
            if ((this.UpdateUSGOperationCompleted == null)) {
                this.UpdateUSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUSGOperationCompleted);
            }
            this.InvokeAsync("UpdateUSG", new object[] {
                        usg}, this.UpdateUSGOperationCompleted, userState);
        }
        
        private void OnUpdateUSGOperationCompleted(object arg) {
            if ((this.UpdateUSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUSGCompleted(this, new UpdateUSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUSG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client DeleteUSG(USG usg) {
            object[] results = this.Invoke("DeleteUSG", new object[] {
                        usg});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUSGAsync(USG usg) {
            this.DeleteUSGAsync(usg, null);
        }
        
        /// <remarks/>
        public void DeleteUSGAsync(USG usg, object userState) {
            if ((this.DeleteUSGOperationCompleted == null)) {
                this.DeleteUSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUSGOperationCompleted);
            }
            this.InvokeAsync("DeleteUSG", new object[] {
                        usg}, this.DeleteUSGOperationCompleted, userState);
        }
        
        private void OnDeleteUSGOperationCompleted(object arg) {
            if ((this.DeleteUSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUSGCompleted(this, new DeleteUSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDailyNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetDailyNo(System.DateTime dt) {
            object[] results = this.Invoke("GetDailyNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetDailyNoAsync(System.DateTime dt) {
            this.GetDailyNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetDailyNoAsync(System.DateTime dt, object userState) {
            if ((this.GetDailyNoOperationCompleted == null)) {
                this.GetDailyNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDailyNoOperationCompleted);
            }
            this.InvokeAsync("GetDailyNo", new object[] {
                        dt}, this.GetDailyNoOperationCompleted, userState);
        }
        
        private void OnGetDailyNoOperationCompleted(object arg) {
            if ((this.GetDailyNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDailyNoCompleted(this, new GetDailyNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMonthlyNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetMonthlyNo(System.DateTime dt) {
            object[] results = this.Invoke("GetMonthlyNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetMonthlyNoAsync(System.DateTime dt) {
            this.GetMonthlyNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetMonthlyNoAsync(System.DateTime dt, object userState) {
            if ((this.GetMonthlyNoOperationCompleted == null)) {
                this.GetMonthlyNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMonthlyNoOperationCompleted);
            }
            this.InvokeAsync("GetMonthlyNo", new object[] {
                        dt}, this.GetMonthlyNoOperationCompleted, userState);
        }
        
        private void OnGetMonthlyNoOperationCompleted(object arg) {
            if ((this.GetMonthlyNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMonthlyNoCompleted(this, new GetMonthlyNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetYearlyNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetYearlyNo(System.DateTime dt) {
            object[] results = this.Invoke("GetYearlyNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetYearlyNoAsync(System.DateTime dt) {
            this.GetYearlyNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetYearlyNoAsync(System.DateTime dt, object userState) {
            if ((this.GetYearlyNoOperationCompleted == null)) {
                this.GetYearlyNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYearlyNoOperationCompleted);
            }
            this.InvokeAsync("GetYearlyNo", new object[] {
                        dt}, this.GetYearlyNoOperationCompleted, userState);
        }
        
        private void OnGetYearlyNoOperationCompleted(object arg) {
            if ((this.GetYearlyNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYearlyNoCompleted(this, new GetYearlyNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Server2Client {
        
        private int countField;
        
        private double valueField;
        
        private string messageField;
        
        private bool resultField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class USG {
        
        private int idField;
        
        private System.DateTime i_DateField;
        
        private int dailyNoField;
        
        private int monthlyNoField;
        
        private string eMRNoField;
        
        private string diagnosisField;
        
        private string receiptNoField;
        
        private string remarksField;
        
        private double chargeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime I_Date {
            get {
                return this.i_DateField;
            }
            set {
                this.i_DateField = value;
            }
        }
        
        /// <remarks/>
        public int DailyNo {
            get {
                return this.dailyNoField;
            }
            set {
                this.dailyNoField = value;
            }
        }
        
        /// <remarks/>
        public int MonthlyNo {
            get {
                return this.monthlyNoField;
            }
            set {
                this.monthlyNoField = value;
            }
        }
        
        /// <remarks/>
        public string EMRNo {
            get {
                return this.eMRNoField;
            }
            set {
                this.eMRNoField = value;
            }
        }
        
        /// <remarks/>
        public string Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public double Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUSGCompletedEventHandler(object sender, GetUSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUSGByIDCompletedEventHandler(object sender, GetUSGByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUSGByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUSGByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUSGByEMRCompletedEventHandler(object sender, GetUSGByEMRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUSGByEMRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUSGByEMRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUSGByDateCompletedEventHandler(object sender, GetUSGByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUSGByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUSGByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUSGByDatesCompletedEventHandler(object sender, GetUSGByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUSGByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUSGByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddUSGCompletedEventHandler(object sender, AddUSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUSGCompletedEventHandler(object sender, UpdateUSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUSGCompletedEventHandler(object sender, DeleteUSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDailyNoCompletedEventHandler(object sender, GetDailyNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDailyNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDailyNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetMonthlyNoCompletedEventHandler(object sender, GetMonthlyNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMonthlyNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMonthlyNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetYearlyNoCompletedEventHandler(object sender, GetYearlyNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYearlyNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYearlyNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591