//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SRHF.wrCasualty {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsCasualtySoap", Namespace="http://tempuri.org/")]
    public partial class wsCasualty : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCasualtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCasualtyByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCasualtyByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCasualtyByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCasualtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCasualtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCasualtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegdNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SerialNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsCasualty() {
            this.Url = global::SRHF.Properties.Settings.Default.SRHF_wrCasualty_wsCasualty;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCasualtyCompletedEventHandler GetCasualtyCompleted;
        
        /// <remarks/>
        public event GetCasualtyByIDCompletedEventHandler GetCasualtyByIDCompleted;
        
        /// <remarks/>
        public event GetCasualtyByDateCompletedEventHandler GetCasualtyByDateCompleted;
        
        /// <remarks/>
        public event GetCasualtyByDatesCompletedEventHandler GetCasualtyByDatesCompleted;
        
        /// <remarks/>
        public event AddCasualtyCompletedEventHandler AddCasualtyCompleted;
        
        /// <remarks/>
        public event UpdateCasualtyCompletedEventHandler UpdateCasualtyCompleted;
        
        /// <remarks/>
        public event DeleteCasualtyCompletedEventHandler DeleteCasualtyCompleted;
        
        /// <remarks/>
        public event RegdNoCompletedEventHandler RegdNoCompleted;
        
        /// <remarks/>
        public event SerialNoCompletedEventHandler SerialNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCasualty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetCasualty() {
            object[] results = this.Invoke("GetCasualty", new object[0]);
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetCasualtyAsync() {
            this.GetCasualtyAsync(null);
        }
        
        /// <remarks/>
        public void GetCasualtyAsync(object userState) {
            if ((this.GetCasualtyOperationCompleted == null)) {
                this.GetCasualtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCasualtyOperationCompleted);
            }
            this.InvokeAsync("GetCasualty", new object[0], this.GetCasualtyOperationCompleted, userState);
        }
        
        private void OnGetCasualtyOperationCompleted(object arg) {
            if ((this.GetCasualtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCasualtyCompleted(this, new GetCasualtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCasualtyByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Casualty GetCasualtyByID(int ID) {
            object[] results = this.Invoke("GetCasualtyByID", new object[] {
                        ID});
            return ((Casualty)(results[0]));
        }
        
        /// <remarks/>
        public void GetCasualtyByIDAsync(int ID) {
            this.GetCasualtyByIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void GetCasualtyByIDAsync(int ID, object userState) {
            if ((this.GetCasualtyByIDOperationCompleted == null)) {
                this.GetCasualtyByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCasualtyByIDOperationCompleted);
            }
            this.InvokeAsync("GetCasualtyByID", new object[] {
                        ID}, this.GetCasualtyByIDOperationCompleted, userState);
        }
        
        private void OnGetCasualtyByIDOperationCompleted(object arg) {
            if ((this.GetCasualtyByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCasualtyByIDCompleted(this, new GetCasualtyByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCasualtyByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetCasualtyByDate(System.DateTime dt) {
            object[] results = this.Invoke("GetCasualtyByDate", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetCasualtyByDateAsync(System.DateTime dt) {
            this.GetCasualtyByDateAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetCasualtyByDateAsync(System.DateTime dt, object userState) {
            if ((this.GetCasualtyByDateOperationCompleted == null)) {
                this.GetCasualtyByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCasualtyByDateOperationCompleted);
            }
            this.InvokeAsync("GetCasualtyByDate", new object[] {
                        dt}, this.GetCasualtyByDateOperationCompleted, userState);
        }
        
        private void OnGetCasualtyByDateOperationCompleted(object arg) {
            if ((this.GetCasualtyByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCasualtyByDateCompleted(this, new GetCasualtyByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCasualtyByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetCasualtyByDates(System.DateTime df, System.DateTime dt) {
            object[] results = this.Invoke("GetCasualtyByDates", new object[] {
                        df,
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetCasualtyByDatesAsync(System.DateTime df, System.DateTime dt) {
            this.GetCasualtyByDatesAsync(df, dt, null);
        }
        
        /// <remarks/>
        public void GetCasualtyByDatesAsync(System.DateTime df, System.DateTime dt, object userState) {
            if ((this.GetCasualtyByDatesOperationCompleted == null)) {
                this.GetCasualtyByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCasualtyByDatesOperationCompleted);
            }
            this.InvokeAsync("GetCasualtyByDates", new object[] {
                        df,
                        dt}, this.GetCasualtyByDatesOperationCompleted, userState);
        }
        
        private void OnGetCasualtyByDatesOperationCompleted(object arg) {
            if ((this.GetCasualtyByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCasualtyByDatesCompleted(this, new GetCasualtyByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCasualty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client AddCasualty(Casualty c) {
            object[] results = this.Invoke("AddCasualty", new object[] {
                        c});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void AddCasualtyAsync(Casualty c) {
            this.AddCasualtyAsync(c, null);
        }
        
        /// <remarks/>
        public void AddCasualtyAsync(Casualty c, object userState) {
            if ((this.AddCasualtyOperationCompleted == null)) {
                this.AddCasualtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCasualtyOperationCompleted);
            }
            this.InvokeAsync("AddCasualty", new object[] {
                        c}, this.AddCasualtyOperationCompleted, userState);
        }
        
        private void OnAddCasualtyOperationCompleted(object arg) {
            if ((this.AddCasualtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCasualtyCompleted(this, new AddCasualtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCasualty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateCasualty(Casualty c) {
            object[] results = this.Invoke("UpdateCasualty", new object[] {
                        c});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCasualtyAsync(Casualty c) {
            this.UpdateCasualtyAsync(c, null);
        }
        
        /// <remarks/>
        public void UpdateCasualtyAsync(Casualty c, object userState) {
            if ((this.UpdateCasualtyOperationCompleted == null)) {
                this.UpdateCasualtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCasualtyOperationCompleted);
            }
            this.InvokeAsync("UpdateCasualty", new object[] {
                        c}, this.UpdateCasualtyOperationCompleted, userState);
        }
        
        private void OnUpdateCasualtyOperationCompleted(object arg) {
            if ((this.UpdateCasualtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCasualtyCompleted(this, new UpdateCasualtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCasualty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client DeleteCasualty(Casualty c) {
            object[] results = this.Invoke("DeleteCasualty", new object[] {
                        c});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCasualtyAsync(Casualty c) {
            this.DeleteCasualtyAsync(c, null);
        }
        
        /// <remarks/>
        public void DeleteCasualtyAsync(Casualty c, object userState) {
            if ((this.DeleteCasualtyOperationCompleted == null)) {
                this.DeleteCasualtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCasualtyOperationCompleted);
            }
            this.InvokeAsync("DeleteCasualty", new object[] {
                        c}, this.DeleteCasualtyOperationCompleted, userState);
        }
        
        private void OnDeleteCasualtyOperationCompleted(object arg) {
            if ((this.DeleteCasualtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCasualtyCompleted(this, new DeleteCasualtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegdNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client RegdNo(System.DateTime dt) {
            object[] results = this.Invoke("RegdNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void RegdNoAsync(System.DateTime dt) {
            this.RegdNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void RegdNoAsync(System.DateTime dt, object userState) {
            if ((this.RegdNoOperationCompleted == null)) {
                this.RegdNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegdNoOperationCompleted);
            }
            this.InvokeAsync("RegdNo", new object[] {
                        dt}, this.RegdNoOperationCompleted, userState);
        }
        
        private void OnRegdNoOperationCompleted(object arg) {
            if ((this.RegdNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegdNoCompleted(this, new RegdNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SerialNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client SerialNo(System.DateTime dt) {
            object[] results = this.Invoke("SerialNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void SerialNoAsync(System.DateTime dt) {
            this.SerialNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void SerialNoAsync(System.DateTime dt, object userState) {
            if ((this.SerialNoOperationCompleted == null)) {
                this.SerialNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSerialNoOperationCompleted);
            }
            this.InvokeAsync("SerialNo", new object[] {
                        dt}, this.SerialNoOperationCompleted, userState);
        }
        
        private void OnSerialNoOperationCompleted(object arg) {
            if ((this.SerialNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SerialNoCompleted(this, new SerialNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Server2Client {
        
        private int countField;
        
        private double valueField;
        
        private string messageField;
        
        private bool resultField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Casualty {
        
        private int idField;
        
        private string regNoField;
        
        private int slNoField;
        
        private System.DateTime regDateField;
        
        private System.DateTime regTimeField;
        
        private string pNameField;
        
        private string addressField;
        
        private int ageField;
        
        private string sexField;
        
        private string diagnosisField;
        
        private string treatmentField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string RegNo {
            get {
                return this.regNoField;
            }
            set {
                this.regNoField = value;
            }
        }
        
        /// <remarks/>
        public int SlNo {
            get {
                return this.slNoField;
            }
            set {
                this.slNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegDate {
            get {
                return this.regDateField;
            }
            set {
                this.regDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegTime {
            get {
                return this.regTimeField;
            }
            set {
                this.regTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PName {
            get {
                return this.pNameField;
            }
            set {
                this.pNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
            }
        }
        
        /// <remarks/>
        public string Treatment {
            get {
                return this.treatmentField;
            }
            set {
                this.treatmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCasualtyCompletedEventHandler(object sender, GetCasualtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCasualtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCasualtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCasualtyByIDCompletedEventHandler(object sender, GetCasualtyByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCasualtyByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCasualtyByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Casualty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Casualty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCasualtyByDateCompletedEventHandler(object sender, GetCasualtyByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCasualtyByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCasualtyByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCasualtyByDatesCompletedEventHandler(object sender, GetCasualtyByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCasualtyByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCasualtyByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddCasualtyCompletedEventHandler(object sender, AddCasualtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCasualtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCasualtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCasualtyCompletedEventHandler(object sender, UpdateCasualtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCasualtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCasualtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteCasualtyCompletedEventHandler(object sender, DeleteCasualtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCasualtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCasualtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegdNoCompletedEventHandler(object sender, RegdNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegdNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegdNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SerialNoCompletedEventHandler(object sender, SerialNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SerialNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SerialNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591