//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SRHF.wrRSBY {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsRSBYSoap", Namespace="http://tempuri.org/")]
    public partial class wsRSBY : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSerialNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRSBYByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRSBYOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRSBYByMRDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRSBYByRemarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertRSBYOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRSBYOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRSBYOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllHealthCareOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHealthCareByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertHCareOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateHCareOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteHCareOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsRSBY() {
            this.Url = global::SRHF.Properties.Settings.Default.SRHF_wrRSBY_wsRSBY;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSerialNoCompletedEventHandler GetSerialNoCompleted;
        
        /// <remarks/>
        public event GetRSBYByIDCompletedEventHandler GetRSBYByIDCompleted;
        
        /// <remarks/>
        public event GetAllRSBYCompletedEventHandler GetAllRSBYCompleted;
        
        /// <remarks/>
        public event GetRSBYByMRDCompletedEventHandler GetRSBYByMRDCompleted;
        
        /// <remarks/>
        public event GetRSBYByRemarksCompletedEventHandler GetRSBYByRemarksCompleted;
        
        /// <remarks/>
        public event InsertRSBYCompletedEventHandler InsertRSBYCompleted;
        
        /// <remarks/>
        public event UpdateRSBYCompletedEventHandler UpdateRSBYCompleted;
        
        /// <remarks/>
        public event DeleteRSBYCompletedEventHandler DeleteRSBYCompleted;
        
        /// <remarks/>
        public event GetAllHealthCareCompletedEventHandler GetAllHealthCareCompleted;
        
        /// <remarks/>
        public event GetHealthCareByIDCompletedEventHandler GetHealthCareByIDCompleted;
        
        /// <remarks/>
        public event InsertHCareCompletedEventHandler InsertHCareCompleted;
        
        /// <remarks/>
        public event UpdateHCareCompletedEventHandler UpdateHCareCompleted;
        
        /// <remarks/>
        public event DeleteHCareCompletedEventHandler DeleteHCareCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSerialNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetSerialNo() {
            object[] results = this.Invoke("GetSerialNo", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetSerialNoAsync() {
            this.GetSerialNoAsync(null);
        }
        
        /// <remarks/>
        public void GetSerialNoAsync(object userState) {
            if ((this.GetSerialNoOperationCompleted == null)) {
                this.GetSerialNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSerialNoOperationCompleted);
            }
            this.InvokeAsync("GetSerialNo", new object[0], this.GetSerialNoOperationCompleted, userState);
        }
        
        private void OnGetSerialNoOperationCompleted(object arg) {
            if ((this.GetSerialNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSerialNoCompleted(this, new GetSerialNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRSBYByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RSBY GetRSBYByID(int ID) {
            object[] results = this.Invoke("GetRSBYByID", new object[] {
                        ID});
            return ((RSBY)(results[0]));
        }
        
        /// <remarks/>
        public void GetRSBYByIDAsync(int ID) {
            this.GetRSBYByIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void GetRSBYByIDAsync(int ID, object userState) {
            if ((this.GetRSBYByIDOperationCompleted == null)) {
                this.GetRSBYByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRSBYByIDOperationCompleted);
            }
            this.InvokeAsync("GetRSBYByID", new object[] {
                        ID}, this.GetRSBYByIDOperationCompleted, userState);
        }
        
        private void OnGetRSBYByIDOperationCompleted(object arg) {
            if ((this.GetRSBYByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRSBYByIDCompleted(this, new GetRSBYByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllRSBY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetAllRSBY() {
            object[] results = this.Invoke("GetAllRSBY", new object[0]);
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRSBYAsync() {
            this.GetAllRSBYAsync(null);
        }
        
        /// <remarks/>
        public void GetAllRSBYAsync(object userState) {
            if ((this.GetAllRSBYOperationCompleted == null)) {
                this.GetAllRSBYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRSBYOperationCompleted);
            }
            this.InvokeAsync("GetAllRSBY", new object[0], this.GetAllRSBYOperationCompleted, userState);
        }
        
        private void OnGetAllRSBYOperationCompleted(object arg) {
            if ((this.GetAllRSBYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRSBYCompleted(this, new GetAllRSBYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRSBYByMRD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetRSBYByMRD(string MRDNo) {
            object[] results = this.Invoke("GetRSBYByMRD", new object[] {
                        MRDNo});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetRSBYByMRDAsync(string MRDNo) {
            this.GetRSBYByMRDAsync(MRDNo, null);
        }
        
        /// <remarks/>
        public void GetRSBYByMRDAsync(string MRDNo, object userState) {
            if ((this.GetRSBYByMRDOperationCompleted == null)) {
                this.GetRSBYByMRDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRSBYByMRDOperationCompleted);
            }
            this.InvokeAsync("GetRSBYByMRD", new object[] {
                        MRDNo}, this.GetRSBYByMRDOperationCompleted, userState);
        }
        
        private void OnGetRSBYByMRDOperationCompleted(object arg) {
            if ((this.GetRSBYByMRDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRSBYByMRDCompleted(this, new GetRSBYByMRDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRSBYByRemarks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetRSBYByRemarks(string Remarks) {
            object[] results = this.Invoke("GetRSBYByRemarks", new object[] {
                        Remarks});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetRSBYByRemarksAsync(string Remarks) {
            this.GetRSBYByRemarksAsync(Remarks, null);
        }
        
        /// <remarks/>
        public void GetRSBYByRemarksAsync(string Remarks, object userState) {
            if ((this.GetRSBYByRemarksOperationCompleted == null)) {
                this.GetRSBYByRemarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRSBYByRemarksOperationCompleted);
            }
            this.InvokeAsync("GetRSBYByRemarks", new object[] {
                        Remarks}, this.GetRSBYByRemarksOperationCompleted, userState);
        }
        
        private void OnGetRSBYByRemarksOperationCompleted(object arg) {
            if ((this.GetRSBYByRemarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRSBYByRemarksCompleted(this, new GetRSBYByRemarksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertRSBY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client InsertRSBY(RSBY r) {
            object[] results = this.Invoke("InsertRSBY", new object[] {
                        r});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRSBYAsync(RSBY r) {
            this.InsertRSBYAsync(r, null);
        }
        
        /// <remarks/>
        public void InsertRSBYAsync(RSBY r, object userState) {
            if ((this.InsertRSBYOperationCompleted == null)) {
                this.InsertRSBYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRSBYOperationCompleted);
            }
            this.InvokeAsync("InsertRSBY", new object[] {
                        r}, this.InsertRSBYOperationCompleted, userState);
        }
        
        private void OnInsertRSBYOperationCompleted(object arg) {
            if ((this.InsertRSBYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRSBYCompleted(this, new InsertRSBYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRSBY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateRSBY(RSBY r) {
            object[] results = this.Invoke("UpdateRSBY", new object[] {
                        r});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRSBYAsync(RSBY r) {
            this.UpdateRSBYAsync(r, null);
        }
        
        /// <remarks/>
        public void UpdateRSBYAsync(RSBY r, object userState) {
            if ((this.UpdateRSBYOperationCompleted == null)) {
                this.UpdateRSBYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRSBYOperationCompleted);
            }
            this.InvokeAsync("UpdateRSBY", new object[] {
                        r}, this.UpdateRSBYOperationCompleted, userState);
        }
        
        private void OnUpdateRSBYOperationCompleted(object arg) {
            if ((this.UpdateRSBYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRSBYCompleted(this, new UpdateRSBYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteRSBY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client DeleteRSBY(int ID) {
            object[] results = this.Invoke("DeleteRSBY", new object[] {
                        ID});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRSBYAsync(int ID) {
            this.DeleteRSBYAsync(ID, null);
        }
        
        /// <remarks/>
        public void DeleteRSBYAsync(int ID, object userState) {
            if ((this.DeleteRSBYOperationCompleted == null)) {
                this.DeleteRSBYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRSBYOperationCompleted);
            }
            this.InvokeAsync("DeleteRSBY", new object[] {
                        ID}, this.DeleteRSBYOperationCompleted, userState);
        }
        
        private void OnDeleteRSBYOperationCompleted(object arg) {
            if ((this.DeleteRSBYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRSBYCompleted(this, new DeleteRSBYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllHealthCare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetAllHealthCare() {
            object[] results = this.Invoke("GetAllHealthCare", new object[0]);
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllHealthCareAsync() {
            this.GetAllHealthCareAsync(null);
        }
        
        /// <remarks/>
        public void GetAllHealthCareAsync(object userState) {
            if ((this.GetAllHealthCareOperationCompleted == null)) {
                this.GetAllHealthCareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllHealthCareOperationCompleted);
            }
            this.InvokeAsync("GetAllHealthCare", new object[0], this.GetAllHealthCareOperationCompleted, userState);
        }
        
        private void OnGetAllHealthCareOperationCompleted(object arg) {
            if ((this.GetAllHealthCareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllHealthCareCompleted(this, new GetAllHealthCareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHealthCareByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HCARE GetHealthCareByID(int ID) {
            object[] results = this.Invoke("GetHealthCareByID", new object[] {
                        ID});
            return ((HCARE)(results[0]));
        }
        
        /// <remarks/>
        public void GetHealthCareByIDAsync(int ID) {
            this.GetHealthCareByIDAsync(ID, null);
        }
        
        /// <remarks/>
        public void GetHealthCareByIDAsync(int ID, object userState) {
            if ((this.GetHealthCareByIDOperationCompleted == null)) {
                this.GetHealthCareByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHealthCareByIDOperationCompleted);
            }
            this.InvokeAsync("GetHealthCareByID", new object[] {
                        ID}, this.GetHealthCareByIDOperationCompleted, userState);
        }
        
        private void OnGetHealthCareByIDOperationCompleted(object arg) {
            if ((this.GetHealthCareByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHealthCareByIDCompleted(this, new GetHealthCareByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertHCare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client InsertHCare(HCARE h) {
            object[] results = this.Invoke("InsertHCare", new object[] {
                        h});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void InsertHCareAsync(HCARE h) {
            this.InsertHCareAsync(h, null);
        }
        
        /// <remarks/>
        public void InsertHCareAsync(HCARE h, object userState) {
            if ((this.InsertHCareOperationCompleted == null)) {
                this.InsertHCareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertHCareOperationCompleted);
            }
            this.InvokeAsync("InsertHCare", new object[] {
                        h}, this.InsertHCareOperationCompleted, userState);
        }
        
        private void OnInsertHCareOperationCompleted(object arg) {
            if ((this.InsertHCareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertHCareCompleted(this, new InsertHCareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateHCare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateHCare(HCARE h) {
            object[] results = this.Invoke("UpdateHCare", new object[] {
                        h});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateHCareAsync(HCARE h) {
            this.UpdateHCareAsync(h, null);
        }
        
        /// <remarks/>
        public void UpdateHCareAsync(HCARE h, object userState) {
            if ((this.UpdateHCareOperationCompleted == null)) {
                this.UpdateHCareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateHCareOperationCompleted);
            }
            this.InvokeAsync("UpdateHCare", new object[] {
                        h}, this.UpdateHCareOperationCompleted, userState);
        }
        
        private void OnUpdateHCareOperationCompleted(object arg) {
            if ((this.UpdateHCareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateHCareCompleted(this, new UpdateHCareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteHCare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client DeleteHCare(int ID) {
            object[] results = this.Invoke("DeleteHCare", new object[] {
                        ID});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteHCareAsync(int ID) {
            this.DeleteHCareAsync(ID, null);
        }
        
        /// <remarks/>
        public void DeleteHCareAsync(int ID, object userState) {
            if ((this.DeleteHCareOperationCompleted == null)) {
                this.DeleteHCareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteHCareOperationCompleted);
            }
            this.InvokeAsync("DeleteHCare", new object[] {
                        ID}, this.DeleteHCareOperationCompleted, userState);
        }
        
        private void OnDeleteHCareOperationCompleted(object arg) {
            if ((this.DeleteHCareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteHCareCompleted(this, new DeleteHCareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RSBY {
        
        private int idField;
        
        private int slNoField;
        
        private string mRDNoField;
        
        private string pNameField;
        
        private string addressField;
        
        private string familyHeadField;
        
        private string contactNoField;
        
        private string wardField;
        
        private System.DateTime admissionDateField;
        
        private System.DateTime dischargeDateField;
        
        private string packagesField;
        
        private double totalBillField;
        
        private double actualAmountField;
        
        private double hospitalShareField;
        
        private string uRNField;
        
        private string remarksField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int SlNo {
            get {
                return this.slNoField;
            }
            set {
                this.slNoField = value;
            }
        }
        
        /// <remarks/>
        public string MRDNo {
            get {
                return this.mRDNoField;
            }
            set {
                this.mRDNoField = value;
            }
        }
        
        /// <remarks/>
        public string PName {
            get {
                return this.pNameField;
            }
            set {
                this.pNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyHead {
            get {
                return this.familyHeadField;
            }
            set {
                this.familyHeadField = value;
            }
        }
        
        /// <remarks/>
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        public string Ward {
            get {
                return this.wardField;
            }
            set {
                this.wardField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AdmissionDate {
            get {
                return this.admissionDateField;
            }
            set {
                this.admissionDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DischargeDate {
            get {
                return this.dischargeDateField;
            }
            set {
                this.dischargeDateField = value;
            }
        }
        
        /// <remarks/>
        public string Packages {
            get {
                return this.packagesField;
            }
            set {
                this.packagesField = value;
            }
        }
        
        /// <remarks/>
        public double TotalBill {
            get {
                return this.totalBillField;
            }
            set {
                this.totalBillField = value;
            }
        }
        
        /// <remarks/>
        public double ActualAmount {
            get {
                return this.actualAmountField;
            }
            set {
                this.actualAmountField = value;
            }
        }
        
        /// <remarks/>
        public double HospitalShare {
            get {
                return this.hospitalShareField;
            }
            set {
                this.hospitalShareField = value;
            }
        }
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HCARE {
        
        private int idField;
        
        private int enrollmentNoField;
        
        private string mRDNoField;
        
        private string pNameField;
        
        private string addressField;
        
        private string familyHeadField;
        
        private double amountClaimedField;
        
        private string diagnosisField;
        
        private System.DateTime admissionDateField;
        
        private System.DateTime dischargeDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int EnrollmentNo {
            get {
                return this.enrollmentNoField;
            }
            set {
                this.enrollmentNoField = value;
            }
        }
        
        /// <remarks/>
        public string MRDNo {
            get {
                return this.mRDNoField;
            }
            set {
                this.mRDNoField = value;
            }
        }
        
        /// <remarks/>
        public string PName {
            get {
                return this.pNameField;
            }
            set {
                this.pNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyHead {
            get {
                return this.familyHeadField;
            }
            set {
                this.familyHeadField = value;
            }
        }
        
        /// <remarks/>
        public double AmountClaimed {
            get {
                return this.amountClaimedField;
            }
            set {
                this.amountClaimedField = value;
            }
        }
        
        /// <remarks/>
        public string Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AdmissionDate {
            get {
                return this.admissionDateField;
            }
            set {
                this.admissionDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DischargeDate {
            get {
                return this.dischargeDateField;
            }
            set {
                this.dischargeDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Server2Client {
        
        private int countField;
        
        private double valueField;
        
        private string messageField;
        
        private bool resultField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetSerialNoCompletedEventHandler(object sender, GetSerialNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSerialNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSerialNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRSBYByIDCompletedEventHandler(object sender, GetRSBYByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRSBYByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRSBYByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RSBY Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RSBY)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllRSBYCompletedEventHandler(object sender, GetAllRSBYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRSBYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRSBYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRSBYByMRDCompletedEventHandler(object sender, GetRSBYByMRDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRSBYByMRDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRSBYByMRDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRSBYByRemarksCompletedEventHandler(object sender, GetRSBYByRemarksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRSBYByRemarksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRSBYByRemarksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InsertRSBYCompletedEventHandler(object sender, InsertRSBYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRSBYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRSBYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateRSBYCompletedEventHandler(object sender, UpdateRSBYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRSBYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRSBYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteRSBYCompletedEventHandler(object sender, DeleteRSBYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRSBYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRSBYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllHealthCareCompletedEventHandler(object sender, GetAllHealthCareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllHealthCareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllHealthCareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetHealthCareByIDCompletedEventHandler(object sender, GetHealthCareByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHealthCareByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHealthCareByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HCARE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HCARE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InsertHCareCompletedEventHandler(object sender, InsertHCareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertHCareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertHCareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateHCareCompletedEventHandler(object sender, UpdateHCareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateHCareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateHCareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteHCareCompletedEventHandler(object sender, DeleteHCareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteHCareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteHCareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591