//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SRHF.wrOPD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsOPDSoap", Namespace="http://tempuri.org/")]
    public partial class wsOPD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOPDByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOPDByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDailyNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMonthlyNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYearlyNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEMRNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsOPD() {
            this.Url = global::SRHF.Properties.Settings.Default.SRHF_wrOPD_wsOPD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOPDCompletedEventHandler GetOPDCompleted;
        
        /// <remarks/>
        public event GetOPDByDateCompletedEventHandler GetOPDByDateCompleted;
        
        /// <remarks/>
        public event GetOPDByDatesCompletedEventHandler GetOPDByDatesCompleted;
        
        /// <remarks/>
        public event AddOPDCompletedEventHandler AddOPDCompleted;
        
        /// <remarks/>
        public event UpdateOPDCompletedEventHandler UpdateOPDCompleted;
        
        /// <remarks/>
        public event DeleteOPDCompletedEventHandler DeleteOPDCompleted;
        
        /// <remarks/>
        public event GetDailyNoCompletedEventHandler GetDailyNoCompleted;
        
        /// <remarks/>
        public event GetMonthlyNoCompletedEventHandler GetMonthlyNoCompleted;
        
        /// <remarks/>
        public event GetYearlyNoCompletedEventHandler GetYearlyNoCompleted;
        
        /// <remarks/>
        public event GetEMRNoCompletedEventHandler GetEMRNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOPD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetOPD() {
            object[] results = this.Invoke("GetOPD", new object[0]);
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetOPDAsync() {
            this.GetOPDAsync(null);
        }
        
        /// <remarks/>
        public void GetOPDAsync(object userState) {
            if ((this.GetOPDOperationCompleted == null)) {
                this.GetOPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOPDOperationCompleted);
            }
            this.InvokeAsync("GetOPD", new object[0], this.GetOPDOperationCompleted, userState);
        }
        
        private void OnGetOPDOperationCompleted(object arg) {
            if ((this.GetOPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOPDCompleted(this, new GetOPDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOPDByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetOPDByDate(System.DateTime dt) {
            object[] results = this.Invoke("GetOPDByDate", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetOPDByDateAsync(System.DateTime dt) {
            this.GetOPDByDateAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetOPDByDateAsync(System.DateTime dt, object userState) {
            if ((this.GetOPDByDateOperationCompleted == null)) {
                this.GetOPDByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOPDByDateOperationCompleted);
            }
            this.InvokeAsync("GetOPDByDate", new object[] {
                        dt}, this.GetOPDByDateOperationCompleted, userState);
        }
        
        private void OnGetOPDByDateOperationCompleted(object arg) {
            if ((this.GetOPDByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOPDByDateCompleted(this, new GetOPDByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOPDByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetOPDByDates(System.DateTime dtFr, System.DateTime dtTo) {
            object[] results = this.Invoke("GetOPDByDates", new object[] {
                        dtFr,
                        dtTo});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetOPDByDatesAsync(System.DateTime dtFr, System.DateTime dtTo) {
            this.GetOPDByDatesAsync(dtFr, dtTo, null);
        }
        
        /// <remarks/>
        public void GetOPDByDatesAsync(System.DateTime dtFr, System.DateTime dtTo, object userState) {
            if ((this.GetOPDByDatesOperationCompleted == null)) {
                this.GetOPDByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOPDByDatesOperationCompleted);
            }
            this.InvokeAsync("GetOPDByDates", new object[] {
                        dtFr,
                        dtTo}, this.GetOPDByDatesOperationCompleted, userState);
        }
        
        private void OnGetOPDByDatesOperationCompleted(object arg) {
            if ((this.GetOPDByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOPDByDatesCompleted(this, new GetOPDByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOPD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client AddOPD(OPD opd) {
            object[] results = this.Invoke("AddOPD", new object[] {
                        opd});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void AddOPDAsync(OPD opd) {
            this.AddOPDAsync(opd, null);
        }
        
        /// <remarks/>
        public void AddOPDAsync(OPD opd, object userState) {
            if ((this.AddOPDOperationCompleted == null)) {
                this.AddOPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOPDOperationCompleted);
            }
            this.InvokeAsync("AddOPD", new object[] {
                        opd}, this.AddOPDOperationCompleted, userState);
        }
        
        private void OnAddOPDOperationCompleted(object arg) {
            if ((this.AddOPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOPDCompleted(this, new AddOPDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOPD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateOPD(OPD opd) {
            object[] results = this.Invoke("UpdateOPD", new object[] {
                        opd});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOPDAsync(OPD opd) {
            this.UpdateOPDAsync(opd, null);
        }
        
        /// <remarks/>
        public void UpdateOPDAsync(OPD opd, object userState) {
            if ((this.UpdateOPDOperationCompleted == null)) {
                this.UpdateOPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOPDOperationCompleted);
            }
            this.InvokeAsync("UpdateOPD", new object[] {
                        opd}, this.UpdateOPDOperationCompleted, userState);
        }
        
        private void OnUpdateOPDOperationCompleted(object arg) {
            if ((this.UpdateOPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOPDCompleted(this, new UpdateOPDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteOPD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client DeleteOPD(OPD opd) {
            object[] results = this.Invoke("DeleteOPD", new object[] {
                        opd});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteOPDAsync(OPD opd) {
            this.DeleteOPDAsync(opd, null);
        }
        
        /// <remarks/>
        public void DeleteOPDAsync(OPD opd, object userState) {
            if ((this.DeleteOPDOperationCompleted == null)) {
                this.DeleteOPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOPDOperationCompleted);
            }
            this.InvokeAsync("DeleteOPD", new object[] {
                        opd}, this.DeleteOPDOperationCompleted, userState);
        }
        
        private void OnDeleteOPDOperationCompleted(object arg) {
            if ((this.DeleteOPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteOPDCompleted(this, new DeleteOPDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDailyNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetDailyNo(System.DateTime dt) {
            object[] results = this.Invoke("GetDailyNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetDailyNoAsync(System.DateTime dt) {
            this.GetDailyNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetDailyNoAsync(System.DateTime dt, object userState) {
            if ((this.GetDailyNoOperationCompleted == null)) {
                this.GetDailyNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDailyNoOperationCompleted);
            }
            this.InvokeAsync("GetDailyNo", new object[] {
                        dt}, this.GetDailyNoOperationCompleted, userState);
        }
        
        private void OnGetDailyNoOperationCompleted(object arg) {
            if ((this.GetDailyNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDailyNoCompleted(this, new GetDailyNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMonthlyNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetMonthlyNo(System.DateTime dt) {
            object[] results = this.Invoke("GetMonthlyNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetMonthlyNoAsync(System.DateTime dt) {
            this.GetMonthlyNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetMonthlyNoAsync(System.DateTime dt, object userState) {
            if ((this.GetMonthlyNoOperationCompleted == null)) {
                this.GetMonthlyNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMonthlyNoOperationCompleted);
            }
            this.InvokeAsync("GetMonthlyNo", new object[] {
                        dt}, this.GetMonthlyNoOperationCompleted, userState);
        }
        
        private void OnGetMonthlyNoOperationCompleted(object arg) {
            if ((this.GetMonthlyNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMonthlyNoCompleted(this, new GetMonthlyNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetYearlyNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetYearlyNo(System.DateTime dt) {
            object[] results = this.Invoke("GetYearlyNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetYearlyNoAsync(System.DateTime dt) {
            this.GetYearlyNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetYearlyNoAsync(System.DateTime dt, object userState) {
            if ((this.GetYearlyNoOperationCompleted == null)) {
                this.GetYearlyNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYearlyNoOperationCompleted);
            }
            this.InvokeAsync("GetYearlyNo", new object[] {
                        dt}, this.GetYearlyNoOperationCompleted, userState);
        }
        
        private void OnGetYearlyNoOperationCompleted(object arg) {
            if ((this.GetYearlyNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYearlyNoCompleted(this, new GetYearlyNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEMRNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetEMRNo(System.DateTime dt) {
            object[] results = this.Invoke("GetEMRNo", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetEMRNoAsync(System.DateTime dt) {
            this.GetEMRNoAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetEMRNoAsync(System.DateTime dt, object userState) {
            if ((this.GetEMRNoOperationCompleted == null)) {
                this.GetEMRNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEMRNoOperationCompleted);
            }
            this.InvokeAsync("GetEMRNo", new object[] {
                        dt}, this.GetEMRNoOperationCompleted, userState);
        }
        
        private void OnGetEMRNoOperationCompleted(object arg) {
            if ((this.GetEMRNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEMRNoCompleted(this, new GetEMRNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Server2Client {
        
        private int countField;
        
        private double valueField;
        
        private string messageField;
        
        private bool resultField;
        
        private System.Data.DataTable dtField;
        
        private System.Data.DataSet dsField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OPD {
        
        private int idField;
        
        private System.DateTime i_DateField;
        
        private int dailyNoField;
        
        private int monthlyNoField;
        
        private int yearlyNoField;
        
        private string eMRNoField;
        
        private int oPDNoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime I_Date {
            get {
                return this.i_DateField;
            }
            set {
                this.i_DateField = value;
            }
        }
        
        /// <remarks/>
        public int DailyNo {
            get {
                return this.dailyNoField;
            }
            set {
                this.dailyNoField = value;
            }
        }
        
        /// <remarks/>
        public int MonthlyNo {
            get {
                return this.monthlyNoField;
            }
            set {
                this.monthlyNoField = value;
            }
        }
        
        /// <remarks/>
        public int YearlyNo {
            get {
                return this.yearlyNoField;
            }
            set {
                this.yearlyNoField = value;
            }
        }
        
        /// <remarks/>
        public string EMRNo {
            get {
                return this.eMRNoField;
            }
            set {
                this.eMRNoField = value;
            }
        }
        
        /// <remarks/>
        public int OPDNo {
            get {
                return this.oPDNoField;
            }
            set {
                this.oPDNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetOPDCompletedEventHandler(object sender, GetOPDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOPDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOPDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetOPDByDateCompletedEventHandler(object sender, GetOPDByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOPDByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOPDByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetOPDByDatesCompletedEventHandler(object sender, GetOPDByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOPDByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOPDByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddOPDCompletedEventHandler(object sender, AddOPDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOPDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOPDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateOPDCompletedEventHandler(object sender, UpdateOPDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOPDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOPDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteOPDCompletedEventHandler(object sender, DeleteOPDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteOPDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteOPDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDailyNoCompletedEventHandler(object sender, GetDailyNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDailyNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDailyNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetMonthlyNoCompletedEventHandler(object sender, GetMonthlyNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMonthlyNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMonthlyNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetYearlyNoCompletedEventHandler(object sender, GetYearlyNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYearlyNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYearlyNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEMRNoCompletedEventHandler(object sender, GetEMRNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEMRNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEMRNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591